version: '3'
services:
  back-end:
    build: ./back-end
    ports:
      - '8080:8080'
    networks:
      - app_network
    restart: on-failure
  front-end:
    build: ./front-end
    ports:
      - '3000:3000'
    networks:
      - app_network
    restart: on-failure
networks:
  app_network:
    driver: bridge