version: '1'
services:
  frontend:
    build:
      context: ./front-end 
    ports:
      - "3000:3000"
    networks:
      - your-network
    depends_on:
      - backend
  backend:
    build:
      context: .  
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"  
    networks:
      - your-network
networks:
  your-network:

    

